### ISSUE TITLE
decoding of `null`

### ISSUE THREAD

**Issue by stla** [jeroenooms/jsonlite#172]
Hello,

It would be nice if `fromJSON` had an option to control the decoding of `null`: either `NULL` or `NA`.

 For example, consider this JSON string:
```
> json
"{\"A\":[null,2],\"B\":[3,\"x\"]}"
```
Then the `null` is converted to `NULL` below, and there is no option to get a `NA` instead.
```
> fromJSON(json, simplifyVector = FALSE)
$A
$A[[1]]
NULL

$A[[2]]
[1] 2


$B
$B[[1]]
[1] 3

$B[[2]]
[1] "x"
```

Cheers.

**Comment by jeroenooms** [comment]
You can do this by setting `simplifyVector = TRUE`.

**Comment by stla** [comment]
Yes, but no... The `3` becomes `"3"` if I do that !

**Comment by jeroenooms** [comment]
Yes, vectors in R are homogeneous so they get coersed into a single type. 

But also note that `NA` does have several types: `NA_integer_`, `NA_real_`, `NA_character_`, etc. That's why we can't "just turn `NULL` into `NA`.

If you want to convert your `NULL` into `NA` you need to do this yourself in the code, because it makes no sense to do this in `fromJSON` without simplifying.

**Comment by stla** [comment]
Ok, I see. Thank you.
