### ISSUE TITLE
R proxy settings not respected on Windows

### ISSUE THREAD

**Issue by huftis** [jeroenooms/jsonlite#43]
On Windows, the ‘fromJSON()’ function doesn’t seem to respect the proxy settings in R.

Example:

```
library(jsonlite)
setInternet2()
d = fromJSON("http://data.ssb.no/api/v0/dataset/49623.json?lang=no")
```

The file is downloaded directly, _not_ using the proxy settings. It's perhaps easiest to see the effect if you change the IE proxy settings to an invalid proxy server.

(The actual result for me is that the file is not downloaded at all, and results in this error message:
    Error in function (type, msg, asError = TRUE)  : couldn't connect to host
The reason is that our corporate firewall blocks all download requests that don't go via our proxy server.)

However, downloading the file using the HTTP support in R works:

```
l = readLines("http://data.ssb.no/api/v0/dataset/49623.json?lang=no",
            encoding="UTF-8", warn=FALSE)
d = fromJSON(l)
```

So if jsonlite would use the built-in download feature of R, as shown above, everything would fine.

> sessionInfo()
> R version 3.1.1 (2014-07-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=Norwegian-Nynorsk_Norway.1252 
[2] LC_CTYPE=Norwegian-Nynorsk_Norway.1252  
[3] LC_MONETARY=Norwegian-Nynorsk_Norway.1252
[4] LC_NUMERIC=C  
[5] LC_TIME=Norwegian-Nynorsk_Norway.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_0.9.12

**Comment by cderv** [comment]
It seems you are using `curl` now and not `Rcurl` anymore. Is it still not possible to use proxy on windows ? 
I do not manage to use it. `HTTP_PROXY` environment variable used by `libcurl` do not work, and `httr::use_proxy` do not work to. 

Do you have a solution ?

**Comment by lfdmotta** [comment]
Hi,

I run into the same problem. This issue is still there in the latest version of jsonlite. There is a simple solution, though.

In the current code of fromJSON, line 89:

`h <- curl::new_handle(useragent = paste("jsonlite /", R.version.string))`

should instead be replaced by 1) a test to see if the system is Windows, and in case this is true, then

`h <- curl::new_handle(useragent = paste("jsonlite /", R.version.string), proxy = curl::ie_get_proxy_for_url())`

Unfortunately it seems that it is not possible to set up a global automatic proxy for handlers in curl under Windows, so that all calls to curl need a new handle with the proxy set.

**Comment by cderv** [comment]
I need to re-test it maybe but I think I managed to make curl works with [Environment Variable that curl options knows about](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html)

**Comment by srowelluf** [comment]
@cderv How did your alternation of the environment variable end up working?  Use a proxy that needs authentication, and was not able to get curl to use it.
