### ISSUE TITLE
New versions of 'jsonlite' can't handle embedded newline characters

### ISSUE THREAD

**Issue by abnova** [jeroenooms/jsonlite#47]
New versions of 'jsonlite' (since version 0.9.12) can't parse JSON values with embedded newline characters. Here's minimal reproducible example:

``` r
json <- '[{"request": "impRQ", "SQL": "
SELECT *
FROM theTable
WHERE a < 100
"}]'

# correct behavior (older versions)
fromJSON(json)
  request                                        SQL
1   impRQ \nSELECT *\nFROM theTable\nWHERE a < 100\n

# incorrect behavior (versions 0.9.12+)
fromJSON(json)
Error in parseJSON(txt) : lexical error: invalid character inside string.
          [{"request": "impRQ", "SQL": " SELECT * FROM theTable WHERE 
                     (right here) ------^
```

**Comment by manniche** [comment]
Using version 0.9.16 I get the lexical error with the following json string:
```{r}
> json <- '[{"request": "A \nString\r with some \n escape sequences\r\n in it"}]'
> jsonlite::fromJSON(json)
Error in parse_string(txt, bigint_as_char) : 
  lexical error: invalid character inside string.
                        [{"request": "A  String  with some   escape se
                     (right here) ------^
```
Both jsonlint and the jsonformatter at curiousconcept.com thinks this is valid json
[jsonformatter link](curl 'http://jsonformatter.curiousconcept.com/process' -H 'Host: jsonformatter.curiousconcept.com' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'X-Requested-With: XMLHttpRequest' -H 'Referer: http://jsonformatter.curiousconcept.com/' --data 'jsondata=%5B%0D%0A++++%7B%0D%0A++++++++%22request%22%3A+%22A+%5CnString%5Cr+with+some+%5Cn+escape+sequences%5Cr%5Cn+in+it%22%0D%0A++++%7D%0D%0A%5D&jsontemplate=1&jsonvalidate=true') (I cannot link to jsonlint, since it uses pure client side js)

**Comment by jeroenooms** [comment]
I think you want:

```r
json <- '[{"request": "A \\nString\\r with some \\n escape sequences\\r\\n in it"}]'

#See what it looks like:
cat(json)
```

This is unrelated to json, if you want to enter a backslash in a string in R, you need to escape it with another backslash. So this

**Comment by manniche** [comment]
Ok, but the server response - which is what I am passing into jsonlite - comes as normal json with single backslashes. I parse the response first, and that gets passed into a `chr`:
```
    tryCatch( response <- getURL( endPoint, ssl.verifyhost=FALSE ),
             error = function( e ){
                 stop('Unable to complete the request, \n',
                         'The message from the server was: \n',
                         e$message)
             })

    tryCatch( jsonResp <- jsonlite::fromJSON( response ),
              error = function( e ){
                stop( 'Could not parse JSON response, \n',
                         'The error message from the server was: \n',
                         e$message)
              })
 ```
I wonder whether this isn't a very normal usecase?

I acknowledge that there is no reason to reopen this issue, the error lies with the input. I could just imagine that the above way of receiving a server reponse and trying to parse it as json is a normal way of doing things. Should there perhaps be a check in jsonlite before the string is parsed? There are other sanity checks in https://github.com/jeroenooms/jsonlite/blob/master/R/fromJSON.R.

**Comment by daroczig** [comment]
@manniche, IMO it's the `getURL` function that processes the `\n` into real line breaks -- before passing to `fromJSON`. If you can, use `fromJSON` directly on the URL.
