### ISSUE TITLE
Mixing of homo and heterogeneous JSON arrays

### ISSUE THREAD

**Issue by robertzk** [jeroenooms/jsonlite#66]
I cannot reproduce this parsing, which works correctly with rjson.

```r
## This is the correct answer.
> rjson::fromJSON('{"should be numeric": [1,2], "should be list": [1, "a"]}')
$`should be numeric`
[1] 1 2

$`should be list`
$`should be list`[[1]]
[1] 1

$`should be list`[[2]]
[1] "a"

## Can jsonlite work correctly with mixed types?
> jsonlite::fromJSON('{"should be numeric": [1,2], "should be list": [1, "a"]}')
$`should be numeric`
[1] 1 2

$`should be list`
[1] "1" "a"

> jsonlite::fromJSON('{"should be numeric": [1,2], "should be list": [1, "a"]}', simplifyVector = FALSE)
$`should be numeric`
$`should be numeric`[[1]]
[1] 1

$`should be numeric`[[2]]
[1] 2

$`should be list`
$`should be list`[[1]]
[1] 1

$`should be list`[[2]]
[1] "a"
```

Is there no way to tell jsonlite to attempt simplification of lists *only if* all list elements are length 1 atomic vectors of the same class? I do not want to coerce `[1, "a"]` to a character vector.

**Comment by jeroenooms** [comment]
This is deliberately not done because it is bad practice. If depending on the content of your data `fromJSON` would return a list for one array and a vector for another array, the code is likely to run into type errors.

Mixing types in JSON arrays should be avoided if possible. If for whatever reason you are stuck with this structure, I recommend you manually simplify the fields you want to simplify using `unlist`, for example:

```r
json <- '{"should be numeric": [1,2], "should be list": [1, "a"]}'
data <- jsonlite::fromJSON(json, simplifyVector = FALSE)
data[["should be numeric"]] <- unlist(data[["should be numeric"]])
```
