### ISSUE TITLE
Replace RCurl with curl

### ISSUE THREAD

**Issue by jeroenooms** [jeroenooms/jsonlite#67]
This will also make it possible to enable stream parsing.

**Comment by karthik** [comment]
:+1:

**Comment by wch** [comment]
Will this mean that, on Linux, installing jsonlite will require libcurl-dev to be installed?

**Comment by jeroenooms** [comment]
I'm not sure yet if this should be a hard dependency or a suggests.

**Comment by jeroenooms** [comment]
What would you prefer? Forcing the dependency or keeping it optional?

**Comment by wch** [comment]
My concern is that if Shiny requires jsonlite, and jsonlite indirectly requires libcurl-dev, that it'll make it more difficult for users to install.

I can see that there are some reasons you'd want curl to be available, but unfortunately it means that any package that uses jsonlite will require Linux users to do the "attempt to install package, get a cryptic compile error, search on Google, find instructions on Stack Overflow, and try again" routine. I know because I've done this many times myself for other packages. So my preference would be to make it optional.

**Comment by jeroenooms** [comment]
Ah okay good to know, I'll make it optional again. I thought from https://github.com/rstudio/shinyapps/issues/120 that you actually preferred to have it as a formal dependency.

**Comment by wch** [comment]
Oh hm, I had forgotten about that issue. What I really want is for everything to just work. :) I think that making curl optional is probably the lesser of the two evils.

**Comment by jeroenooms** [comment]
Haha okay. Also `curl` is much easier to install than `RCurl` and it will give a [helpful error message](https://github.com/jeroenooms/curl/blob/master/configure#L22) if libcurl is missing.

**Comment by jeroenooms** [comment]
Ok I have [reverted](https://github.com/jeroenooms/jsonlite/commit/ee1884f2805ad1b0a5f086a176f1d7da0720eb46) the last commit. The curl dependency is now back in *Suggests* rather than *Imports*.

**Comment by jeroenooms** [comment]
Fixed in jsonlite 0.9.15.

**Comment by shivanshu1086** [comment]
Hey @jeroen, How did you solve that issue can you please tell me about that bit..?
Like how you replace that package with CURL instead of Rcurl
